[package]
name = "readable"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "readable"
path = "src/bin.rs"

[lib]

[dependencies]
anyhow = "1.0.66"
axum = { version = "0.6.1", features = ["headers"] }
shuttle-service = { version = "0.8.0", features = ["web-axum"], optional = true }
sync_wrapper = "0.1.1"
readable-readability = "0.3.0"
tokio = { version = "1.20.1", features = ["full"], optional = true }
url = "2.3.1"
reqwest = "0.11.13"
chrono = "0.4.23"
kuchiki = "0.8.1"

[features]
default = ["shuttle"]
shuttle = ["shuttle-service"]
local = ["dep:tokio"]
